-- MySQL Script generated by MySQL Workbench
-- Mon Jan 22 21:23:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema minxianfd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minxianfd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minxianfd` DEFAULT CHARACTER SET utf8 ;
USE `minxianfd` ;

-- -----------------------------------------------------
-- Table `minxianfd`.`admin_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`admin_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n\n主键id',
  `username` VARCHAR(25) NOT NULL COMMENT '\n\n\n用户名',
  `password` CHAR(32) NOT NULL COMMENT '\n\n\n密码',
  `type` TINYINT(1) UNSIGNED NOT NULL COMMENT '\n类型？（0>超级管理员，1>普通管理员）',
  `status` TINYINT(1) UNSIGNED NOT NULL COMMENT '\n状态？（0>正常，1>冻结）',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '后台用户表';


-- -----------------------------------------------------
-- Table `minxianfd`.`weapp_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`weapp_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `openid` VARCHAR(45) NOT NULL COMMENT '\n绑定用户openid',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '小程序用户表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_house_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_house_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `habitable_room` TINYINT(1) UNSIGNED NOT NULL COMMENT '\nX室?',
  `living_room` TINYINT(1) UNSIGNED NOT NULL COMMENT '\nX厅？',
  `shower_room` TINYINT(1) UNSIGNED NOT NULL COMMENT '\nX卫？',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源基础信息户型表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_basics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_basics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `housing_resource_genre` VARCHAR(25) NOT NULL COMMENT '\n房源类型？0’其它，1’住宅，2‘别墅，3’写字楼，4’商铺',
  `decorate_degree` VARCHAR(25) NOT NULL COMMENT '\n装修程度？0‘其它，1‘豪华装修，2’精装修，3‘中等装修，4’简装修，5‘毛坯',
  `orientation` VARCHAR(25) NOT NULL COMMENT '\n朝向？0’南北，1‘南，2’东南，3‘东，4’西南，5’北，6‘西，7’东西，8’东北，9‘西北',
  `hm_house_type_id` INT UNSIGNED NOT NULL COMMENT '\n关联户型主键id',
  `area` DECIMAL(5,2) UNSIGNED NOT NULL COMMENT '\nX平方米？',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`),
  INDEX `fk_basics_house_type1_idx` (`hm_house_type_id` ASC),
  CONSTRAINT `fk_basics_house_type1`
    FOREIGN KEY (`hm_house_type_id`)
    REFERENCES `minxianfd`.`hm_house_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '房源基础信息表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_min_xian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_min_xian` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `town_village` VARCHAR(45) NOT NULL COMMENT '\n城镇',
  `sort` TINYINT(3) UNSIGNED NOT NULL COMMENT '\n排序？数字越小越靠前',
  `type` TINYINT(1) UNSIGNED NOT NULL COMMENT '\n类型？0’城镇，1>乡村',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源岷县地区表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_area` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `hm_min_xian_id` INT UNSIGNED NOT NULL,
  `address` VARCHAR(255) NOT NULL COMMENT '\n街道及小区',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`),
  INDEX `fk_hm_area_hm_min_xian1_idx` (`hm_min_xian_id` ASC),
  CONSTRAINT `fk_hm_area_hm_min_xian1`
    FOREIGN KEY (`hm_min_xian_id`)
    REFERENCES `minxianfd`.`hm_min_xian` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '房源区域表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_floor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `total_floor` TINYINT(3) UNSIGNED NOT NULL COMMENT '\n总楼层',
  `present_floor` TINYINT(3) UNSIGNED NOT NULL COMMENT '\n当前楼层',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源小区楼层表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_doorplate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_doorplate` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `building` TINYINT(3) UNSIGNED NOT NULL COMMENT '\nX号楼',
  `unit` TINYINT(3) UNSIGNED NOT NULL COMMENT '\nX单元',
  `household` TINYINT(3) UNSIGNED NOT NULL COMMENT '\nX户',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源小区门牌表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_community`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_community` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `cname` VARCHAR(45) NOT NULL COMMENT '\n小区名称',
  `hm_floor_id` INT UNSIGNED NOT NULL,
  `hm_doorplate_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hm_community_hm_floor1_idx` (`hm_floor_id` ASC),
  INDEX `fk_hm_community_hm_doorplate1_idx` (`hm_doorplate_id` ASC),
  CONSTRAINT `fk_hm_community_hm_floor1`
    FOREIGN KEY (`hm_floor_id`)
    REFERENCES `minxianfd`.`hm_floor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_community_hm_doorplate1`
    FOREIGN KEY (`hm_doorplate_id`)
    REFERENCES `minxianfd`.`hm_doorplate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '房源小区信息表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_lease_manner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_lease_manner` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `cname` VARCHAR(45) NOT NULL COMMENT '\n名称',
  `sort` TINYINT(3) UNSIGNED NOT NULL COMMENT '\n排序？数字越小越靠前',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源出租方式';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_payment_method` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cname` VARCHAR(45) NOT NULL COMMENT '\n名称',
  `sort` TINYINT(3) UNSIGNED NOT NULL COMMENT '\n排序？数字越小越靠前',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源付款方式表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_ancillary_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_ancillary_facility` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `cname` VARCHAR(45) NOT NULL COMMENT '\n名称',
  `sort` TINYINT(3) UNSIGNED NOT NULL COMMENT '\n排序？数字越小越靠前',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源配套设施表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_lease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_lease` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `hm_lease_manner_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源租赁方式表主键id',
  `hm_payment_method_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源付款方式表主键id',
  `hm_ancillary_facility_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源配套设置表主键id',
  `rent` DECIMAL(14,2) UNSIGNED NOT NULL COMMENT '\n租金？X元/月',
  PRIMARY KEY (`id`),
  INDEX `fk_hm_lease_hm_lease_manner1_idx` (`hm_lease_manner_id` ASC),
  INDEX `fk_hm_lease_hm_payment_method1_idx` (`hm_payment_method_id` ASC),
  INDEX `fk_hm_lease_hm_ancillary_facility1_idx` (`hm_ancillary_facility_id` ASC),
  CONSTRAINT `fk_hm_lease_hm_lease_manner1`
    FOREIGN KEY (`hm_lease_manner_id`)
    REFERENCES `minxianfd`.`hm_lease_manner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_lease_hm_payment_method1`
    FOREIGN KEY (`hm_payment_method_id`)
    REFERENCES `minxianfd`.`hm_payment_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_lease_hm_ancillary_facility1`
    FOREIGN KEY (`hm_ancillary_facility_id`)
    REFERENCES `minxianfd`.`hm_ancillary_facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '房源租赁信息表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_view_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_view_images` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `path` VARCHAR(255) NULL COMMENT '\n路径',
  `sort` TINYINT(3) UNSIGNED NOT NULL COMMENT '\n排序？数字越小越靠前',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源环景图片表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_housing_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_housing_resource` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `title` VARCHAR(255) NOT NULL COMMENT '\n标题',
  `describe` TEXT(20000) NOT NULL COMMENT '\n描述',
  `trait` VARCHAR(255) NOT NULL COMMENT '\n特点',
  `hm_view_images_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源环景图片表主键id',
  `in_time` VARCHAR(45) NOT NULL COMMENT '\n入住时间',
  PRIMARY KEY (`id`),
  INDEX `fk_hm_housing_resource_hm_view_images1_idx` (`hm_view_images_id` ASC),
  CONSTRAINT `fk_hm_housing_resource_hm_view_images1`
    FOREIGN KEY (`hm_view_images_id`)
    REFERENCES `minxianfd`.`hm_view_images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '房源信息表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_owner` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `description` TEXT(20000) NOT NULL COMMENT '\n描述',
  `demand` TEXT(20000) NOT NULL COMMENT '\n要求',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源业主信息表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_landlord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_landlord` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `cname` VARCHAR(45) NOT NULL COMMENT '\n姓名',
  `phone` VARCHAR(45) NOT NULL COMMENT '\n手机号码',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源房东信息表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_promotion_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_promotion_cost` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `day` INT UNSIGNED NOT NULL COMMENT '\n天数',
  `cost` DECIMAL(14,2) UNSIGNED NOT NULL COMMENT '\n费用',
  `sort` TINYINT(3) UNSIGNED NOT NULL COMMENT '\n排序？数字越小越靠前',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源置顶推广费用表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_promotion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `hm_promotion_cost_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源置顶推广费用表主键id',
  `start_time` INT(10) UNSIGNED NOT NULL COMMENT '\n开始时间',
  `end_time` INT(10) UNSIGNED NOT NULL COMMENT '\n结束时间',
  `status` TINYINT(1) UNSIGNED NOT NULL COMMENT '\n状态管理？0·启用，1·弃用',
  PRIMARY KEY (`id`),
  INDEX `fk_hm_promotion_hm_promotion_cost1_idx` (`hm_promotion_cost_id` ASC),
  CONSTRAINT `fk_hm_promotion_hm_promotion_cost1`
    FOREIGN KEY (`hm_promotion_cost_id`)
    REFERENCES `minxianfd`.`hm_promotion_cost` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '房源置顶推广表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_counselor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_counselor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `head_portrait` VARCHAR(255) NOT NULL COMMENT '\n头像',
  `cname` VARCHAR(45) NOT NULL COMMENT '\n姓名',
  `telephone` VARCHAR(45) NOT NULL COMMENT '\n电话号码',
  `status` TINYINT(1) UNSIGNED NOT NULL COMMENT '\n状态？0·启用，1·弃用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源租房顾问表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_promotion_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_promotion_time` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n\n主键id',
  `start_time` INT(10) UNSIGNED NOT NULL COMMENT '\n开始时间',
  `end_time` INT(10) UNSIGNED NOT NULL COMMENT '\n结束时间',
  `status` TINYINT(1) UNSIGNED NOT NULL COMMENT '\n状态？0·正常，1·停用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '房源模块推广时间表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_landlord_rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_landlord_rent` (
  `id` INT UNSIGNED NOT NULL COMMENT '\n主键id',
  `weapp_user_id` INT UNSIGNED NOT NULL COMMENT '\n关联小程序用户表主键id',
  `hm_basics_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源基础信息表主键id',
  `hm_area_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源区域表主键id',
  `hm_community_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源小区信息表主键id',
  `hm_lease_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源租赁信息表主键id',
  `hm_housing_resource_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源信息表主键id',
  `hm_owner_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源业主信息表主键id',
  `hm_landlord_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源房东信息表主键id',
  `hm_promotion_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源置顶推广表主键id',
  `hm_promotion_time_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源模块推广时间表主键id',
  `hm_counselor_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源租房顾问表主键id',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  `status` TINYINT(1) UNSIGNED NOT NULL COMMENT '\n状态？0·启用，1·弃用',
  PRIMARY KEY (`id`),
  INDEX `fk_hm_landlord_rent_weapp_user_idx` (`weapp_user_id` ASC),
  INDEX `fk_hm_landlord_rent_basics1_idx` (`hm_basics_id` ASC),
  INDEX `fk_hm_landlord_rent_hm_area1_idx` (`hm_area_id` ASC),
  INDEX `fk_hm_landlord_rent_hm_community1_idx` (`hm_community_id` ASC),
  INDEX `fk_hm_landlord_rent_hm_lease1_idx` (`hm_lease_id` ASC),
  INDEX `fk_hm_landlord_rent_hm_housing_resource1_idx` (`hm_housing_resource_id` ASC),
  INDEX `fk_hm_landlord_rent_hm_owner1_idx` (`hm_owner_id` ASC),
  INDEX `fk_hm_landlord_rent_hm_landlord1_idx` (`hm_landlord_id` ASC),
  INDEX `fk_hm_landlord_rent_hm_promotion1_idx` (`hm_promotion_id` ASC),
  INDEX `fk_hm_landlord_rent_hm_counselor1_idx` (`hm_counselor_id` ASC),
  INDEX `fk_hm_landlord_rent_hm_promotion_time1_idx` (`hm_promotion_time_id` ASC),
  CONSTRAINT `fk_hm_landlord_rent_weapp_user`
    FOREIGN KEY (`weapp_user_id`)
    REFERENCES `minxianfd`.`weapp_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_landlord_rent_basics1`
    FOREIGN KEY (`hm_basics_id`)
    REFERENCES `minxianfd`.`hm_basics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_landlord_rent_hm_area1`
    FOREIGN KEY (`hm_area_id`)
    REFERENCES `minxianfd`.`hm_area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_landlord_rent_hm_community1`
    FOREIGN KEY (`hm_community_id`)
    REFERENCES `minxianfd`.`hm_community` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_landlord_rent_hm_lease1`
    FOREIGN KEY (`hm_lease_id`)
    REFERENCES `minxianfd`.`hm_lease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_landlord_rent_hm_housing_resource1`
    FOREIGN KEY (`hm_housing_resource_id`)
    REFERENCES `minxianfd`.`hm_housing_resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_landlord_rent_hm_owner1`
    FOREIGN KEY (`hm_owner_id`)
    REFERENCES `minxianfd`.`hm_owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_landlord_rent_hm_landlord1`
    FOREIGN KEY (`hm_landlord_id`)
    REFERENCES `minxianfd`.`hm_landlord` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_landlord_rent_hm_promotion1`
    FOREIGN KEY (`hm_promotion_id`)
    REFERENCES `minxianfd`.`hm_promotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_landlord_rent_hm_counselor1`
    FOREIGN KEY (`hm_counselor_id`)
    REFERENCES `minxianfd`.`hm_counselor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_landlord_rent_hm_promotion_time1`
    FOREIGN KEY (`hm_promotion_time_id`)
    REFERENCES `minxianfd`.`hm_promotion_time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '房源模块房东出租表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_owner_collect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_owner_collect` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `hm_landlord_rent_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源模块房东出租表主键id',
  `weapp_user_id` INT UNSIGNED NOT NULL COMMENT '\n关联小程序用户表主键id',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`),
  INDEX `fk_hm_owner_wanted_hm_landlord_rent1_idx` (`hm_landlord_rent_id` ASC),
  INDEX `fk_hm_owner_wanted_weapp_user1_idx` (`weapp_user_id` ASC),
  CONSTRAINT `fk_hm_owner_wanted_hm_landlord_rent1`
    FOREIGN KEY (`hm_landlord_rent_id`)
    REFERENCES `minxianfd`.`hm_landlord_rent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_owner_wanted_weapp_user1`
    FOREIGN KEY (`weapp_user_id`)
    REFERENCES `minxianfd`.`weapp_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '房源模块业主收藏表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_owner_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_owner_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `hm_landlord_rent_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源模块房东出租表主键id',
  `weapp_user_id` INT UNSIGNED NOT NULL COMMENT '\n关联小程序用户表主键id',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`),
  INDEX `fk_hm_owner_record_hm_landlord_rent1_idx` (`hm_landlord_rent_id` ASC),
  INDEX `fk_hm_owner_record_weapp_user1_idx` (`weapp_user_id` ASC),
  CONSTRAINT `fk_hm_owner_record_hm_landlord_rent1`
    FOREIGN KEY (`hm_landlord_rent_id`)
    REFERENCES `minxianfd`.`hm_landlord_rent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_owner_record_weapp_user1`
    FOREIGN KEY (`weapp_user_id`)
    REFERENCES `minxianfd`.`weapp_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '房源模块业主看房记录表';


-- -----------------------------------------------------
-- Table `minxianfd`.`hm_owner_estimate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`hm_owner_estimate` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `hm_landlord_rent_id` INT UNSIGNED NOT NULL COMMENT '\n关联房源模块房东出租表主键id',
  `weapp_user_id` INT UNSIGNED NOT NULL COMMENT '\n关联小程序用户表主键id',
  `content` VARCHAR(255) NOT NULL COMMENT '\n评价内容',
  `ctime` INT(10) NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`),
  INDEX `fk_hm_owner_estimate_hm_landlord_rent1_idx` (`hm_landlord_rent_id` ASC),
  INDEX `fk_hm_owner_estimate_weapp_user1_idx` (`weapp_user_id` ASC),
  CONSTRAINT `fk_hm_owner_estimate_hm_landlord_rent1`
    FOREIGN KEY (`hm_landlord_rent_id`)
    REFERENCES `minxianfd`.`hm_landlord_rent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hm_owner_estimate_weapp_user1`
    FOREIGN KEY (`weapp_user_id`)
    REFERENCES `minxianfd`.`weapp_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '房源模块业主评价表';


-- -----------------------------------------------------
-- Table `minxianfd`.`information_module_banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`information_module_banner` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `path` VARCHAR(255) NOT NULL COMMENT '\n路径',
  `sort` TINYINT(3) NOT NULL COMMENT '\n排序？数字越小越靠前',
  `ctime` INT(10) NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '资讯模块banner';


-- -----------------------------------------------------
-- Table `minxianfd`.`information_module_about`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minxianfd`.`information_module_about` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '\n主键id',
  `content` TEXT(20000) NOT NULL COMMENT '\n内容',
  `ctime` INT(10) UNSIGNED NOT NULL COMMENT '\n时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '资讯模块关于我们表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
